-
    hosts:
        - mesos_masters
        - mesos_slaves
    sudo: yes
    tasks:
        -
            name: Add user to docker group
            user:
                name: ubuntu
                append: yes
                groups: docker

- hosts: all
  sudo: True
  roles:
    - { role: ansible-docker, tags: ['os-tools'] }
    - { role: ansible-mesos, mesos_version: "0.22.1", tags: ['mesos', 'platforms'] }
