- hosts: all
  sudo: True
  roles:
    - { role: ansible-docker, docker_opts: '"--default-ulimit nofile=262144:262144"', tags: ['os-tools'] }

-
    hosts: all
    sudo: True
    name: Add user to docker group
    tasks:
      - user: name={{user}} append=yes groups=docker

- hosts: mesos_masters
  sudo: True
  roles:
    - { role: ansible-mesos, mesos_version: "0.23.0", mesos_install_mode: master, zookeeper_hostnames: "{{ groups.mesos_masters | join(':2181,')}}:2181" , tags: ['mesos', 'platforms'] }

- hosts: mesos_slaves
  sudo: True
  roles:
    - { role: ansible-mesos, mesos_version: "0.23.0", mesos_install_mode: slave, zookeeper_hostnames: "{{ groups.mesos_masters | join(':2181,')}}:2181", tags: ['mesos', 'platforms'] }


